version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: bekindusername
      POSTGRES_PASSWORD: bekindpassword
      POSTGRES_DB: bekinddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
