services:
  backend:
    build: ./backend
    container_name: backend-development
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    volumes:
      - ~/be-kind-app/backend:/usr/src/app
    env_file:
      - ~/be-kind-app/backend/.env
  frontend:
    build: ./frontend
    container_name: frontend-development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ~/be-kind-app/frontend:/usr/src/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: bekinduser
      POSTGRES_PASSWORD: bekindpassword
      POSTGRES_DB: bekinddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

